package com.e.lms.generic;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

import javax.activation.DataSource;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPath;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;

public class variables
{
	//**********************************STRING VARIABLES************************************************
	
	public static String BrowserName;
	public static String applicationurl;
	public static String MachineName;
	public static String username;
	public static String password;
	public static String coursecode;
	public static String coursetitle;
	public static String typecode;
	public static String typediscription;
	public static String organizationcode;
	public static String organization;
	public static String unittype;
	public static String unit;
	public static String unitcode;
	public static String unitname;
	public static String unittypecode;
	public static String unittypename;
	public static String hierarchicallyunder;
	public static String country;
	public static String countrycode;
	public static String statecode;
	public static String statename;
	public static String citycode;
	public static String placecode;
	public static String placename;
	public static String agencycode;
	public static String agencyname;
	public static String state;
	public static String city;
	public static String place;
	public static String placetype;
	public static String sector;
	public static String address;
	public static String pincode;
	public static String contactnumber;
	public static String website;
	public static String employeecode;
	public static String title;
	public static String firstname;
	public static String middlename;
	public static String lastname;
	public static String introduction;
	public static String searchunit;
	public static String departmentcode;
	public static String department;
	public static String grade;
	public static String designationcode;
	public static String designation;
	public static String searchsupervisor;
	public static String role;
	public static String employeetype;
	public static String employeecategory;
	public static String language;
	public static String dateofbirth;
	public static String mobileno;
	public static String officialemail;
	public static String facilitytype;
	public static String category;
	public static String assetcode;
	public static String facilitydescription;
	public static String additionaldescription;
	public static String elearning;
	public static String resource;
	public static String classroom;
	public static String topic;
	public static String rowdata;
	public static String ibvalue;
	public static String lables;
	public static String rowdatascore;
	public static String celldata;
	public static String mainwindow;
	public static String childwindow;
	public static String contentwindowurl;
	public static String expectedcontentwindowurl = "http://192.168.91.27:8019/Courses/ResourceCourseLauncher.aspx";
	public static String expectedelearningcontentwindowurl = "http://192.168.91.27:8019/Courses";
	public static String actualurl;
	public static String actualtitle;
	public static String expectedurl;
	public static String expectedtitle;
	public static String imagename;
	public static String albumname;
	public static String actualinprogressurl;
	public static String expectedinprogressurl;
	public static String rowdataassessment;
	public static String scorevalue;
	public static String submitmessage;
	public static String expectedsubmsg;
	public static String actualresulturl;
	public static String expectedresulturl;
	public static String resultpagetitle;
	public static String resultpageexpectedtitle;
	public static String resultfailmessage;
	public static String reattmassessmentpage;
	public static String reattmexpectedpage;
	public static String resultpassmessage;
	public static String reultpassexpectedpmsg;
	public static String actualcertificateurl;
	public static String expectedcertificateurl;
	public static String tooltipmessage;
	public static String options;
	public static String options1;
	public static String options2;
	public static String options3;
	public static String options4;
	public static String options5;
	public static String optionText;
	public static String listitem;
	public static String questioncategory;
	public static String trainingtype;
	public static String questiongroup;
	public static String expectedanswertype;
	public static String optionsequence;
	public static String noofoptions;
	public static String questiontext;
	public static String newstype;
	public static String newstitle;
	public static String date;
	public static String validitydate;
	public static String imagefile;
	public static String pdffile;
	public static String file;
	public static String fileToUpload;
	public static String newsdescription;
	public static String discussiontopic;
	public static String publicationtitle;
	public static String publicationdescription;
	public static String externallink;
	public static String externallinkdescription;
	public static String messagefrom;
	public static String messagebrief;
	public static String messageshort;
	public static String messagelong;
	public static String photogallery;
	public static String gradecode;
	public static String gradename;
	public static String reporttograde;
	public static String mandatorymessage;
	public static String group;
	public static String remarks;
	public static String holidaytitle;
	public static String fromdate;
	public static String todate;
	public static String coverage;
	public static String remark;
	public static String applicationname;
	public static String loginboxcolor;
	public static String menubagroundcolor;
	public static String functioncode;
	public static String functionname;
	public static String subfunctioncode;
	public static String subfunctionname;
	public static String keyparameter;
	public static String parametervalue;
	public static String generalquetions;
	public static String simplicitylevel;
	public static String questiontype;
	public static String questionstyle;
	public static String questioncount;
	public static String questionmarks;
	public static String questiontime;
	public static String questionclass;
	public static String datanotavailable;
	public static String optiontype;
	public static String imageheight;
	public static String imagewidth;
	public static String certificateimageheight = "510";
	public static String certificateimagewidth = "720";
	public static String synopsis;
	public static String objective;
	public static String author;
	public static String headingtext;
	public static String hometext;
	public static String welcometext;
	public static String interactiontext;
	public static String calendartext;
	public static String profiletext;
	public static String createnotetext;
	public static String logouttext;
	public static String releasenotestext;
	public static String copyrighttext;
	public static String sectorcode;
	public static String sectorname;
	public static String surveyname;
	public static String norespondent;
	public static String purpose;
	public static String authority;
	public static String contentsubject;
	public static String searchuser;
	public static String CurrentPassword;
	public static String NewPassword;
	public static String ReTypePassword;
	public static String objects;
	public static String competencycategorycode;
	public static String competencycategoryname;
	public static String competencycode;
	public static String competencyname;
	public static String competencydescription;
	public static String employee;
	public static String associatetype;
	public static String associatename;
	public static String applicability;
	public static String categorycode;
	public static String categoryname;
	public static String subcategorycode;
	public static String subcategory;
	public static String objectdescription;
	public static String startuppage;
	public static String compatibility;
	public static String keywordsforsearch;
	public static String assessmenttype;
	public static String trainertype;
	public static String batchsize;
	public static String applicabletoallemployee;
	public static String applicabletoallassociate;
	public static String applicabletoallguest;
	public static String feedback;
	public static String assessment;
	public static String awardmedal;
	public static String preassessment;
	public static String certificate;
	public static String minimunparticipant;
	public static String maximumparticipant;
	public static String monthnamefirst;
	public static String monthnamesecond;
	public static String monthnamethird;
	public static String monthnamefourth;
	public static String paginationvalue;
	public static String coursedatavalue;
	public static String courselaunchvalue;
	public static String previewdivtext;
	public static String legenttext;
	public static String discussionmaincomment;
	public static String discussionsubcomment;
	public static String outputstring;
	public static String logoimage;
	public static String homepagebanner;
	public static String homepagefooter;
	public static String homepagebagroundimage;
	public static String innerpagebanner;
	public static String innerpagefooter;
	public static String location;
	public static String seats;
	public static String nominateduser;
	public static String nooffaciliator;
	public static String servicetax;
	public static String venuecost;
	public static String professionalfees;
	public static String travel;
	public static String lodging;
	public static String boarding;
	public static String localconvey;
	public static String ptravel;
	public static String plodging;
	public static String pboarding;
	public static String plocalconvey;
	public static String projector;
	public static String screen;
	public static String certificateprinting;
	public static String workbooks;
	public static String handout;
	public static String props;
	public static String miscellaneous;
	public static String designcost;
	public static String operationmessage;
	public static String scheduleduration;
	public static String totalbudget;
	public static String durationschedule;
	public static String costperparticipant;
	public static String costperparticipantperday;
	public static String facilitatortotalbudget;
	public static String participanttotalbudget;
	public static String infrastructuretotalbudget;
	public static String schedulecode;
	public static String contentcost;
	public static String placecost;
	public static String academy;
	public static String trainer;
	public static String startdate;
	public static String enddate;
	public static String starttime;
	public static String endtime;
	public static String registrationenddate;
	public static String eventlogo;
	public static String registrationorganization;
	public static String trainingplace;
	public static String schedulecase;
	public static String exscheduledate;
	public static String newschedulestartdate;
	public static String newscheduleenddate;
	public static String newregistrationdate;
	public static String newschedulestarttime;
	public static String newscheduleendtime;
	public static String status;
	public static String cancellationreason;
	public static String agencytype;
	public static String academycode;
	public static String academyname;
	public static String existingposition;
	public static String copydesignation;
	public static String copygrade;
	
		
	//**********************************INTEGER VARIABLES***********************************************
	
	public static boolean use_sg=false;
	public static int pagenumber;
	public static int pno;
	public static boolean IsAssessment;
	public static boolean IsFeedback;
	public static boolean IsCertificate;
	public static boolean mainloop;
	public static boolean subloop;
	public static int allrows;
	public static int tablecells;
	public static int totalpage;
	public static int allrowsassessment;
	public static int value;
	public static int sizeofbuttons;
	public static int countofobjects;
	public static int passingscoremarks;
	public static boolean IsElearningChecked;
	public static boolean IsResourceChecked;
	public static boolean IsClassroomChecked;
	public static boolean IsDownloadCertificate;
	public static int allrowsscore;
	public static boolean IsScore;
	public static int trow;
	public static int i;
	public static int j;
	public static int event;
	public static int scorm;
	public static int duration;
	public static int passingpercentage;
	public static int noofattempts;
	public static int score;
	public static int assigned;
	public static int completed;
	public static int inprogress;
	public static int notstarted;
	public static int expectedassigned;
	
	
	//**********************************ARRAY VARIABLES*************************************************
	
	public static String[] SplitedTestData;
	public static String[] TestData;
	public static String[] rawvalue;
	public static String[] rawvalue1;
	public static ArrayList allWindowHandles;
	public static File[] listOfFiles;
	public static File myFile;
	
	//***********************************LIST<WEB ELEMENT>**********************************************
	
	public static List<WebElement> rowCount;
	public static List<WebElement> table;
	public static List<WebElement> cells;
	public static Select select;
	public static List<WebElement> quebuttons;
	public static List<WebElement> readablestable;
	public static List<WebElement> readablescells;
	public static List<WebElement> tablerowdata;
	public static List<WebElement> option;
	public static List<WebElement> totaldropdown;
	public static List<WebElement> totalinputbox;
	public static List<WebElement> allElements;
	
	//***********************************WEB ELEMENT****************************************************
	
	public static WebElement element;
	public static WebElement content;
	public static WebElement graph;
	public static WebElement downloadcertificatelink;
	public static WebElement downloadcertificateimage;
	public static WebElement tabchart;
	public static WebElement cell;
	public static WebElement SelectValue;
	public static WebElement assessmentstartbutton;
	public static WebElement submitbutton;
	public static WebElement launchbutton;
	public static WebElement courselaunchbutton;
	public static WebElement previewbutton;
	public static WebElement requestbutton;
	public static WebElement unavailabilitybutton;
	public static WebElement scorecarddiv;
	public static WebElement values;
	public static WebElement tooltip;
	public static WebElement report;
	public static WebElement dropdown;
	public static WebElement count;
	public static WebDriver frameDriver;
	public static WebElement coursetype;
	public static WebElement nextbutton;
	public static WebElement Previousbutton;
	public static WebElement catalogueverification;
	
	
	
	//**********************************WebDriver VARIABLES***************************************************

	public static WebDriver driver;
	public static WebDriverWait wait;
	public static DesiredCapabilities dc;
	
	//***********************************FrameWork Variables**************************************************
	
	public static int totalTC;
	public static int tc;
	public static boolean bol;
	public static int totalstepsforthisTC;
	public static int step;
	public static String stepname;
	public static String stepParameterValue;
	public static int method;
	public static Method[] allmethods;
	public static Method desiredmethod;
	public static int startIteration;
	public static int endIteration;
	public static int iterate;
	public static boolean stepvalue;
		
	//****************************************XML Operation Variables*****************************************
	
	public static DocumentBuilderFactory docBuilderFactory;
	public static DocumentBuilder docBuilder;
	public static Document doc=null;
	public static XPath xPath=null;
	public static String expression;
	public static NodeList nodeList;
	public static int result;
	
	//**********************************************TestData Reader*******************************************
	
	public static String filepath;
	public static String returnStr;
	public static FileReader fr; 
	public static BufferedReader br;
	public static String input;
	public static int countline;
	
	//********************************************TestLogger***************************************************
	
	public static String ExecutionLogFileName;
	public static String FunctionalLogFileName;
	public static FileWriter eoutLog;
	public static FileWriter foutLog;
	public static String lineseparator;
	
	//*****************************************Send Mail*******************************************************
	
	//public static SendMail smtpMailSender;
	public static boolean debug;
	public static Authenticator auth;
	public static Session session;
	public static Message msg;
	public static InternetAddress addressFrom;
	public static Multipart multipart;
	public static DataSource source;
	public static InternetAddress[] addressTo;
	public static SendMail smtpMailSender;
	
	
}
